<?php
/**
 * Created by PhpStorm.
 * User: afidoss
 * Date: 22/06/16
 * Time: 17:24
 */

namespace Planner\UserBundle\Validator\Constraints;


use Symfony\Component\Validator\Constraint;

class AntiDoublonMI extends Constraint
{
    public $message = "Impossible d'engeristrer deux ministres active pour le même ministère";
    public $role='ROLE_MI_MI';

    public function validatedBy()
    {
        return 'conseil_antidoublon_mi'; // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getTargets()
    {
        return self::CLASS_CONSTRAINT;
    }


}