<?php
/**
 * Created by PhpStorm.
 * User: afidoss
 * Date: 22/06/16
 * Time: 17:24
 */

namespace Utils\Validators\Constraints;


use Utils\Validators\Constraints\UniqueReferenceValidator;
use Symfony\Component\Validator\Constraint;

class UniqueReference extends Constraint
{
    public $message = "IL ne peut avoir deux Sécrétaires generals.";
    public $role="ROLE_SGG_SG";
    public $property = 'code';

    public function validatedBy()
    {
        return UniqueReferenceValidator::class; // TODO: Change the autogenerated stub
        //return 'conseil_antidoublon_sgg'; // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getTargets()
    {
        return self::CLASS_CONSTRAINT;
    }

}